### ISSUE TITLE
ShadowEngine crash

### ISSUE THREAD

**Issue by ItzDennisz** [ItzDennisz/Hellbound#2]
Sometimes the game crashes on launch with an IndexOutOfBoundsException.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: X
	at net.Hellbound.Renderer.ShadowEngine.Render(ShadowEngine.java:324)
	at net.Hellbound.Gui.GuiPlay.Render(GuiPlay.java:95)
	at net.Hellbound.GuiManager.Render(GuiManager.java:18)
	at net.Hellbound.Hellbound.<init>(Hellbound.java:61)
	at net.Hellbound.Hellbound.main(Hellbound.java:24)

**Comment by ItzDennisz** [comment]
Fixed.
